name: Deploy to Vercel
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install -g vercel@32.5.1  # Using stable version

      - name: Verify Project Access
        run: |
          vercel whoami --token ${{ secrets.VERCEL_TOKEN }}
          vercel link --yes --token ${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Production Deploy
        run: |
          vercel deploy --prod --yes \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            --build-env REACT_APP_VERSION=${{ github.sha }}
